In [143]:
import numpy as np
def createsudukugrid():
    grid = np.zeros((9, 9), dtype=int)
    for row in range(9):
        for col in range(9):
            value = (row * 3 + row // 3 + col) % 9 + 1
            grid[row, col] = value
    np.random.shuffle(grid)
    np.random.shuffle(grid.T)
    
    print(grid)
    return grid

s=createsudukugrid()
print(rowcheck(s))
print(columncheck(s))
print(boxcheck(s))



[[4 8 9 6 3 2 5 1 7]
 [1 5 6 3 9 8 2 7 4]
 [7 2 3 9 6 5 8 4 1]
 [9 4 5 2 8 7 1 6 3]
 [8 3 4 1 7 6 9 5 2]
 [3 7 8 5 2 1 4 9 6]
 [6 1 2 8 5 4 7 3 9]
 [2 6 7 4 1 9 3 8 5]
 [5 9 1 7 4 3 6 2 8]]
[]
[]
[1, 2, 3, 4, 5, 6, 7, 8]


In [144]:

def rowcheck(grid):
    rows_with_error=[]
    l=0
    for row in grid:
        dict={}
        for i in row:
            if i in dict:
                dict[i]=dict[i]+1
            else:
                dict[i]=1
        if len(dict)!=9:
            rows_with_error.append(l)
        l=l+1
    return rows_with_error


def columncheck(grid):
    columns_with_error=[]
    grid = np.array(grid)  # Convert the input list to a NumPy array
    for i in range(9):
        column=grid[:,i]
        dict={}
        for j in column:
            if j in dict:
                dict[j]=dict[j]+1
            else:
                dict[j]=1
        if len(dict)!=9:
            columns_with_error.append(i)
    return columns_with_error

def boxcheck(grid):
    boxes_with_error=[]
    for i in range(3):
        for j in range(3):
            box = [grid[x][y] for x in range(i * 3, i * 3 + 3) for y in range(j * 3, j * 3 + 3)]
            box = np.reshape(box, (3, 3)) 
            dict={}
            for k in box:
                for l in k:
                    if l in dict:
                        dict[l]=dict[l]+1
                    else:
                        dict[l]=1
            if len(dict)!=9:
                boxes_with_error.append(i * 3 + j)
    return boxes_with_error

 

def fitness(grid):
    count=0
    s1=rowcheck(grid)
    s2=columncheck(grid)
    s3=boxcheck(grid)
    count=len(s1)+len(s2)+len(s3)
    return count

def Row_repetitions(row):
    counts = {}
    for num in row:
        if num in counts:
            return num,np.where(row == num)
        counts[num] = 1
    return False  
    
def Rswap(grid):
    for i, row in enumerate(grid):
        if Row_repetitions(row): 
            new_grid=[row.copy() for row in grid]
            num , index= Row_repetitions(row)
            for colindex in index[0]:
                for j in range(9):
                    temp=grid[j][colindex]
                    grid[j][colindex]=num
                    grid[i][colindex]=temp
                    f1=fitness(grid)
                    if f1==0:
                        print("sol foundr1")
                        return grid
                    gg=Cswap(grid)
                    f1=fitness(gg)
                    if f1==0:
                        print("--------------------------------")
                        print(gg)
                        print("sol foundr2")
                        return gg
                    
                    else:
                        grid=[row.copy() for row in new_grid]
    return grid  
                        
def Column_repetitions(column):
    counts = {}
    for num in column:
        if num in counts:
            return num, np.where(column == num)
        counts[num] = 1
    return False
def box_repetitions(box):
    counts = {}
    for num in box.flatten():
        if num in counts:
            return num, np.where(box == num)
        counts[num] = 1
    return False
def Cswap(grid):
    grid = np.array(grid)
    for colindex in range(9):
        column = grid[:, colindex]
        if Column_repetitions(column):
            new_grid = grid.copy()
            num, index = Column_repetitions(column)
            for rowindex in index[0]:
                for j in range(9):
                    temp = grid[rowindex][j]
                    grid[rowindex][j] = num
                    grid[rowindex][colindex] = temp
                    f1 = fitness(grid)
                    if f1 == 0:
                        print("sol foundc")
                        print(grid)
                        return grid
                    else:
                        grid = new_grid.copy()
    return grid
    

        
                       

In [145]:
def solution(grid):
    grid=np.array(grid)
    grid1=grid.copy()
    print("row errors",rowcheck(grid))
    print("col errors",columncheck(grid))
    print("box errors",boxcheck(grid))
    final=Rswap(grid)
    if fitness(final)==0:
        corrections = 0
        for i in range(9):
            for j in range(9):
                if final[i][j] != grid[i][j]:
                    corrections += 1
        return final,corrections
    final=Cswap(grid1)
    if fitness(final)==0:
        corrections = 0
        for i in range(9):
            for j in range(9):
                if final[i][j] != grid[i][j]:
                    corrections += 1
        return final,corrections
    

In [146]:
grid=[[6,2,4, 5,3,4, 1,8,7],
      [5,1,9, 7,2,8, 6,3,4],
      [8,3,7, 6,1,9, 2,9,5],
      [1,4,3, 8,6,5, 7,2,9],
      [9,5,8, 2,4,7, 3,6,1],
      [7,6,2, 3,9,1, 4,5,8],
      [3,7,1, 9,5,6, 8,4,2],
      [4,9,6, 1,8,2, 5,7,3],
      [2,8,5, 4,7,3, 9,1,6]]
s=solution(grid)
ol = [array.tolist() for array in s[0]]

print("row errors",rowcheck(ol))
print("col errors",columncheck(ol))
print("box errors",boxcheck(ol))
print ("corrections", s[1])
ol

row errors [0, 2]
col errors []
box errors []
sol foundr1
row errors []
col errors []
box errors []
corrections 2


[[6, 2, 4, 5, 3, 9, 1, 8, 7],
 [5, 1, 9, 7, 2, 8, 6, 3, 4],
 [8, 3, 7, 6, 1, 4, 2, 9, 5],
 [1, 4, 3, 8, 6, 5, 7, 2, 9],
 [9, 5, 8, 2, 4, 7, 3, 6, 1],
 [7, 6, 2, 3, 9, 1, 4, 5, 8],
 [3, 7, 1, 9, 5, 6, 8, 4, 2],
 [4, 9, 6, 1, 8, 2, 5, 7, 3],
 [2, 8, 5, 4, 7, 3, 9, 1, 6]]

In [147]:
grid = [[6,2,4, 5,3,9, 1,8,7],
        [5,1,9, 7,2,8, 6,3,4],
        [8,3,7, 6,1,4, 2,9,5],
        [1,4,3, 8,6,5, 7,2,9],
        [9,5,8, 2,4,7, 3,6,1],
        [7,6,2, 3,9,1, 4,5,8],
        [3,7,1, 9,5,6, 8,4,2],
        [4,9,6, 1,8,2, 5,7,3],
        [2,8,5, 4,6,3, 9,1,7]]
s=solution(grid)
ol = [array.tolist() for array in s[0]]

print("row errors",rowcheck(ol))
print("col errors",columncheck(ol))
print("box errors",boxcheck(ol))
print ("corrections", s[1])
ol

row errors []
col errors [4, 8]
box errors [7, 8]
sol foundc
[[6 2 4 5 3 9 1 8 7]
 [5 1 9 7 2 8 6 3 4]
 [8 3 7 6 1 4 2 9 5]
 [1 4 3 8 6 5 7 2 9]
 [9 5 8 2 4 7 3 6 1]
 [7 6 2 3 9 1 4 5 8]
 [3 7 1 9 5 6 8 4 2]
 [4 9 6 1 8 2 5 7 3]
 [2 8 5 4 7 3 9 1 6]]
row errors []
col errors []
box errors []
corrections 2


[[6, 2, 4, 5, 3, 9, 1, 8, 7],
 [5, 1, 9, 7, 2, 8, 6, 3, 4],
 [8, 3, 7, 6, 1, 4, 2, 9, 5],
 [1, 4, 3, 8, 6, 5, 7, 2, 9],
 [9, 5, 8, 2, 4, 7, 3, 6, 1],
 [7, 6, 2, 3, 9, 1, 4, 5, 8],
 [3, 7, 1, 9, 5, 6, 8, 4, 2],
 [4, 9, 6, 1, 8, 2, 5, 7, 3],
 [2, 8, 5, 4, 7, 3, 9, 1, 6]]

In [148]:
grid = [[6,2,4, 5,3,9, 1,8,7],
        [5,7,9, 7,2,8, 6,3,4],
        [8,3,7, 6,1,4, 2,9,5],
        [1,4,3, 8,6,5, 7,2,9],
        [9,5,8, 2,4,7, 3,6,1],
        [7,6,2, 3,9,1, 4,5,8],
        [3,1,1, 9,5,6, 8,4,2],
        [4,9,6, 1,8,2, 5,7,3],
        [2,8,5, 4,6,3, 9,1,7]]
s=solution(grid)
ol = [array.tolist() for array in s[0]]

print("row errors",rowcheck(ol))
print("col errors",columncheck(ol))
print("box errors",boxcheck(ol))
print ("corrections", s[1])
ol


row errors [1, 6]
col errors [4, 8]
box errors [0, 6, 7, 8]
sol foundc
[[6 2 4 5 3 9 1 8 7]
 [5 1 9 7 2 8 6 3 4]
 [8 3 7 6 1 4 2 9 5]
 [1 4 3 8 6 5 7 2 9]
 [9 5 8 2 4 7 3 6 1]
 [7 6 2 3 9 1 4 5 8]
 [3 7 1 9 5 6 8 4 2]
 [4 9 6 1 8 2 5 7 3]
 [2 8 5 4 7 3 9 1 6]]
--------------------------------
[[6 2 4 5 3 9 1 8 7]
 [5 1 9 7 2 8 6 3 4]
 [8 3 7 6 1 4 2 9 5]
 [1 4 3 8 6 5 7 2 9]
 [9 5 8 2 4 7 3 6 1]
 [7 6 2 3 9 1 4 5 8]
 [3 7 1 9 5 6 8 4 2]
 [4 9 6 1 8 2 5 7 3]
 [2 8 5 4 7 3 9 1 6]]
sol foundr2
row errors []
col errors []
box errors []
corrections 5


[[6, 2, 4, 5, 3, 9, 1, 8, 7],
 [5, 1, 9, 7, 2, 8, 6, 3, 4],
 [8, 3, 7, 6, 1, 4, 2, 9, 5],
 [1, 4, 3, 8, 6, 5, 7, 2, 9],
 [9, 5, 8, 2, 4, 7, 3, 6, 1],
 [7, 6, 2, 3, 9, 1, 4, 5, 8],
 [3, 7, 1, 9, 5, 6, 8, 4, 2],
 [4, 9, 6, 1, 8, 2, 5, 7, 3],
 [2, 8, 5, 4, 7, 3, 9, 1, 6]]

In [149]:
ol = [array.tolist() for array in s[0]]

print("row errors",rowcheck(ol))
print("col errors",columncheck(ol))
print("box errors",boxcheck(ol))

row errors []
col errors []
box errors []
